services:
  # Main service container
  my_openai_frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: my_openai_frontend:pydev
    container_name: my_openai_frontend
    volumes:
      - ../:/workspace
    working_dir: /workspace
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: tail -f /dev/null

  # React development container
  my_openai_frontend_react:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ts
    image: my_openai_frontend:tsdev
    container_name: my_openai_frontend-react-dev
    volumes:
      - ../:/workspace
    working_dir: /workspace/react-app
    ports:
      - "8080:8080"
    restart: unless-stopped
    command: tail -f /dev/null

  # PostgreSQL database
  postgres:
    image: postgres:latest
    container_name: my_openai_frontend_postgres
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ai_platform_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local